# @package _global_
log_level: INFO
save_logs: false  # Set to true to save all logs to a file
sampling_interval: 1 # Sample 1 time per 1 second

defaults:
  - _self_
  - model: distilgpt2 # tiny model for debugging
  - device: auto
  - scenario: simple_llm

reporter:
  type: json
